# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/MainWindow.ui'
#
# Created: Sat Jan 28 22:31:43 2012
#      by: pyside-uic 0.2.11 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1071, 799)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.simulationView = SimulationView(self.widget)
        self.simulationView.setObjectName("simulationView")
        self.verticalLayout.addWidget(self.simulationView)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.zoomSlider = QtGui.QSlider(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomSlider.sizePolicy().hasHeightForWidth())
        self.zoomSlider.setSizePolicy(sizePolicy)
        self.zoomSlider.setMinimumSize(QtCore.QSize(200, 0))
        self.zoomSlider.setMinimum(-10)
        self.zoomSlider.setMaximum(10)
        self.zoomSlider.setProperty("value", 0)
        self.zoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoomSlider.setInvertedAppearance(False)
        self.zoomSlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.zoomSlider.setObjectName("zoomSlider")
        self.horizontalLayout.addWidget(self.zoomSlider)
        self.zoomOutButton = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomOutButton.sizePolicy().hasHeightForWidth())
        self.zoomOutButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/zoomOut"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomOutButton.setIcon(icon)
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.horizontalLayout.addWidget(self.zoomOutButton)
        self.zoomInButton = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomInButton.sizePolicy().hasHeightForWidth())
        self.zoomInButton.setSizePolicy(sizePolicy)
        self.zoomInButton.setMinimumSize(QtCore.QSize(0, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/zoomIn"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomInButton.setIcon(icon1)
        self.zoomInButton.setArrowType(QtCore.Qt.NoArrow)
        self.zoomInButton.setObjectName("zoomInButton")
        self.horizontalLayout.addWidget(self.zoomInButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addWidget(self.widget)
        self.agentTree = AgentTreeView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.agentTree.sizePolicy().hasHeightForWidth())
        self.agentTree.setSizePolicy(sizePolicy)
        self.agentTree.setMinimumSize(QtCore.QSize(0, 0))
        self.agentTree.setObjectName("agentTree")
        self.horizontalLayout_2.addWidget(self.agentTree)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1071, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSimulation = QtGui.QMenu(self.menubar)
        self.menuSimulation.setObjectName("menuSimulation")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuVehicle = QtGui.QMenu(self.menubar)
        self.menuVehicle.setEnabled(False)
        self.menuVehicle.setObjectName("menuVehicle")
        self.menuRoad = QtGui.QMenu(self.menubar)
        self.menuRoad.setEnabled(False)
        self.menuRoad.setObjectName("menuRoad")
        self.menuJunction = QtGui.QMenu(self.menubar)
        self.menuJunction.setEnabled(False)
        self.menuJunction.setObjectName("menuJunction")
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setIconSize(QtCore.QSize(16, 16))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionQuit = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/quit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon2)
        self.actionQuit.setMenuRole(QtGui.QAction.QuitRole)
        self.actionQuit.setIconVisibleInMenu(True)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSimStart = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/play"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSimStart.setIcon(icon3)
        self.actionSimStart.setIconVisibleInMenu(True)
        self.actionSimStart.setObjectName("actionSimStart")
        self.actionSimPause = QtGui.QAction(MainWindow)
        self.actionSimPause.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/pause"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSimPause.setIcon(icon4)
        self.actionSimPause.setVisible(False)
        self.actionSimPause.setIconVisibleInMenu(True)
        self.actionSimPause.setObjectName("actionSimPause")
        self.actionStatistics = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/statistics"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStatistics.setIcon(icon5)
        self.actionStatistics.setIconVisibleInMenu(True)
        self.actionStatistics.setObjectName("actionStatistics")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setMenuRole(QtGui.QAction.AboutRole)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSimStop = QtGui.QAction(MainWindow)
        self.actionSimStop.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/stop"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSimStop.setIcon(icon6)
        self.actionSimStop.setVisible(True)
        self.actionSimStop.setIconVisibleInMenu(True)
        self.actionSimStop.setObjectName("actionSimStop")
        self.actionVehicleRemove = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/remove"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVehicleRemove.setIcon(icon7)
        self.actionVehicleRemove.setVisible(False)
        self.actionVehicleRemove.setIconVisibleInMenu(True)
        self.actionVehicleRemove.setObjectName("actionVehicleRemove")
        self.actionRoadClose = QtGui.QAction(MainWindow)
        self.actionRoadClose.setCheckable(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/close"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRoadClose.setIcon(icon8)
        self.actionRoadClose.setVisible(False)
        self.actionRoadClose.setIconVisibleInMenu(True)
        self.actionRoadClose.setObjectName("actionRoadClose")
        self.actionRoadSetSpeedLimit = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/speedLimit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRoadSetSpeedLimit.setIcon(icon9)
        self.actionRoadSetSpeedLimit.setVisible(False)
        self.actionRoadSetSpeedLimit.setIconVisibleInMenu(True)
        self.actionRoadSetSpeedLimit.setObjectName("actionRoadSetSpeedLimit")
        self.actionJunctionClose = QtGui.QAction(MainWindow)
        self.actionJunctionClose.setIcon(icon8)
        self.actionJunctionClose.setVisible(False)
        self.actionJunctionClose.setIconVisibleInMenu(True)
        self.actionJunctionClose.setObjectName("actionJunctionClose")
        self.actionJunctionSwitchLights = QtGui.QAction(MainWindow)
        self.actionJunctionSwitchLights.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/lights"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJunctionSwitchLights.setIcon(icon10)
        self.actionJunctionSwitchLights.setVisible(False)
        self.actionJunctionSwitchLights.setIconVisibleInMenu(True)
        self.actionJunctionSwitchLights.setObjectName("actionJunctionSwitchLights")
        self.actionToggleAgentProperties = QtGui.QAction(MainWindow)
        self.actionToggleAgentProperties.setCheckable(True)
        self.actionToggleAgentProperties.setChecked(True)
        self.actionToggleAgentProperties.setVisible(True)
        self.actionToggleAgentProperties.setObjectName("actionToggleAgentProperties")
        self.actionToggleAgentList = QtGui.QAction(MainWindow)
        self.actionToggleAgentList.setCheckable(True)
        self.actionToggleAgentList.setChecked(True)
        self.actionToggleAgentList.setVisible(True)
        self.actionToggleAgentList.setObjectName("actionToggleAgentList")
        self.actionRoadSpawnVehicle = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/add"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRoadSpawnVehicle.setIcon(icon11)
        self.actionRoadSpawnVehicle.setVisible(False)
        self.actionRoadSpawnVehicle.setIconVisibleInMenu(True)
        self.actionRoadSpawnVehicle.setObjectName("actionRoadSpawnVehicle")
        self.actionSimSettings = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/settings2"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSimSettings.setIcon(icon12)
        self.actionSimSettings.setIconVisibleInMenu(True)
        self.actionSimSettings.setObjectName("actionSimSettings")
        self.actionLoadMap = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/world"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoadMap.setIcon(icon13)
        self.actionLoadMap.setIconVisibleInMenu(True)
        self.actionLoadMap.setObjectName("actionLoadMap")
        self.actionZoomIn = QtGui.QAction(MainWindow)
        self.actionZoomIn.setIcon(icon1)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtGui.QAction(MainWindow)
        self.actionZoomOut.setIcon(icon)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.menuFile.addAction(self.actionLoadMap)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuSimulation.addAction(self.actionSimSettings)
        self.menuSimulation.addAction(self.actionSimStart)
        self.menuSimulation.addAction(self.actionSimStop)
        self.menuSimulation.addAction(self.actionSimPause)
        self.menuSimulation.addSeparator()
        self.menuSimulation.addAction(self.actionStatistics)
        self.menuHelp.addAction(self.actionAbout)
        self.menuVehicle.addAction(self.actionVehicleRemove)
        self.menuRoad.addAction(self.actionRoadClose)
        self.menuRoad.addAction(self.actionRoadSetSpeedLimit)
        self.menuRoad.addAction(self.actionRoadSpawnVehicle)
        self.menuJunction.addAction(self.actionJunctionClose)
        self.menuJunction.addAction(self.actionJunctionSwitchLights)
        self.menuWindow.addAction(self.actionToggleAgentProperties)
        self.menuWindow.addAction(self.actionZoomIn)
        self.menuWindow.addAction(self.actionZoomOut)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSimulation.menuAction())
        self.menubar.addAction(self.menuVehicle.menuAction())
        self.menubar.addAction(self.menuRoad.menuAction())
        self.menubar.addAction(self.menuJunction.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionLoadMap)
        self.toolBar.addAction(self.actionSimSettings)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSimStart)
        self.toolBar.addAction(self.actionSimPause)
        self.toolBar.addAction(self.actionSimStop)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionVehicleRemove)
        self.toolBar.addAction(self.actionRoadClose)
        self.toolBar.addAction(self.actionRoadSetSpeedLimit)
        self.toolBar.addAction(self.actionRoadSpawnVehicle)
        self.toolBar.addAction(self.actionJunctionClose)
        self.toolBar.addAction(self.actionJunctionSwitchLights)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionSimStart, QtCore.SIGNAL("triggered()"), MainWindow.startSimulation)
        QtCore.QObject.connect(self.actionSimPause, QtCore.SIGNAL("triggered()"), MainWindow.pauseSimulation)
        QtCore.QObject.connect(self.actionSimStop, QtCore.SIGNAL("triggered()"), MainWindow.stopSimulation)
        QtCore.QObject.connect(self.zoomInButton, QtCore.SIGNAL("clicked()"), self.actionZoomIn.trigger)
        QtCore.QObject.connect(self.zoomOutButton, QtCore.SIGNAL("clicked()"), self.actionZoomOut.trigger)
        QtCore.QObject.connect(self.actionZoomIn, QtCore.SIGNAL("triggered()"), self.simulationView.zoomIn)
        QtCore.QObject.connect(self.actionZoomOut, QtCore.SIGNAL("triggered()"), self.simulationView.zoomOut)
        QtCore.QObject.connect(self.zoomSlider, QtCore.SIGNAL("valueChanged(int)"), self.simulationView.setZoom)
        QtCore.QObject.connect(self.actionLoadMap, QtCore.SIGNAL("triggered()"), MainWindow.loadMap)
        QtCore.QObject.connect(self.simulationView, QtCore.SIGNAL("zoomChanged(int)"), self.zoomSlider.setValue)
        QtCore.QObject.connect(self.actionToggleAgentProperties, QtCore.SIGNAL("toggled(bool)"), self.agentTree.setVisible)
        QtCore.QObject.connect(self.agentTree, QtCore.SIGNAL("agentSelected(QString)"), self.simulationView.selectAgent)
        QtCore.QObject.connect(self.simulationView, QtCore.SIGNAL("agentSelected(QString)"), self.agentTree.selectAgent)
        QtCore.QObject.connect(self.agentTree, QtCore.SIGNAL("agentSelected(QString)"), self.simulationView.centerOnAgent)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Traffic", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomOutButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomInButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSimulation.setTitle(QtGui.QApplication.translate("MainWindow", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuVehicle.setTitle(QtGui.QApplication.translate("MainWindow", "Vehicle", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRoad.setTitle(QtGui.QApplication.translate("MainWindow", "Road", None, QtGui.QApplication.UnicodeUTF8))
        self.menuJunction.setTitle(QtGui.QApplication.translate("MainWindow", "Junction", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindow.setTitle(QtGui.QApplication.translate("MainWindow", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimStart.setText(QtGui.QApplication.translate("MainWindow", "&Start", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimStart.setShortcut(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimPause.setText(QtGui.QApplication.translate("MainWindow", "&Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimPause.setShortcut(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStatistics.setText(QtGui.QApplication.translate("MainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimStop.setShortcut(QtGui.QApplication.translate("MainWindow", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVehicleRemove.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRoadClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRoadSetSpeedLimit.setText(QtGui.QApplication.translate("MainWindow", "Speed Limit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRoadSetSpeedLimit.setToolTip(QtGui.QApplication.translate("MainWindow", "Speed Limit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJunctionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJunctionSwitchLights.setText(QtGui.QApplication.translate("MainWindow", "Switch Lights", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToggleAgentProperties.setText(QtGui.QApplication.translate("MainWindow", "Agent Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToggleAgentList.setText(QtGui.QApplication.translate("MainWindow", "Agent List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRoadSpawnVehicle.setText(QtGui.QApplication.translate("MainWindow", "Spawn Vehicle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRoadSpawnVehicle.setToolTip(QtGui.QApplication.translate("MainWindow", "Spawn Vehicle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadMap.setText(QtGui.QApplication.translate("MainWindow", "&Load Map...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setText(QtGui.QApplication.translate("MainWindow", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setToolTip(QtGui.QApplication.translate("MainWindow", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setShortcut(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setText(QtGui.QApplication.translate("MainWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setToolTip(QtGui.QApplication.translate("MainWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setShortcut(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))

from SimulationView import SimulationView
from AgentTreeView import AgentTreeView
from res import qrc_gfx
from res import qrc_icons
